name: Test

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Setup node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '16.5.0'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: |
          yarn test
